---
- name: "Plugin Install: Z-Probe Offset"
  pip:
    name: "https://framagit.org/razer/octoprint_z_probe_offset/-/archive/latest/octoprint_z_probe_offset-latest.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_z_offset == "y" or install_z_offset == "Y"
  tags:
    - plugins

- name: "Plugin Install: Detail Progress"
  pip:
    name: "https://github.com/tpmullan/OctoPrint-DetailedProgress/archive/master.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_detail_progress == "y" or install_detail_progress == "Y"
  tags:
    - plugins

- name: "Plugin Install: Filament Manager"
  pip:
    name: "https://github.com/bitsy-ai/OctoPrint-FilamentManager/zipball/fix-python-10-compat"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_filament_manager == "y" or install_filament_manager == "Y"
  tags:
    - plugins

- name: "Plugin Install: Print History"
  pip:
    name: "https://github.com/imrahil/OctoPrint-PrintHistory/archive/master.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_print_history == "y" or install_print_history == "Y"
  tags:
    - plugins

- name: "Plugin Install: PrintTime Genius"
  pip:
    name: "https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/master.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_printtime_genius == "y" or install_printtime_genius == "Y"
  tags:
    - plugins

- name: "Plugin Install: Slicer Thumbnails"
  pip:
    name: "https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/archive/master.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_slicer_thumbs == "y" or install_slicer_thumbs == "Y"
  tags:
    - plugins

- name: "Plugin Install: Top Temp"
  pip:
    name: "https://github.com/LazeMSS/OctoPrint-TopTemp/archive/main.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_top_temp == "y" or install_top_temp == "Y"
  tags:
    - plugins

- name: "Plugin Install: UI Customizer"
  pip:
    name: "https://github.com/LazeMSS/OctoPrint-UICustomizer/archive/main.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_ui_custom == "y" or install_ui_custom == "Y"
  tags:
    - plugins

- name: "Plugin Install: Cancel Object"
  pip:
    name: "https://github.com/paukstelis/OctoPrint-Cancelobject/archive/master.zip"
    state: present
    virtualenv: "{{ install_dir }}/.venv"
    virtualenv_command: virtualenv
    virtualenv_python: python3
  when: install_cancel_objects == "y" or install_cancel_objects == "Y"
  tags:
    - plugins