---
- hosts: all
  vars_prompt:
    - name: "printer_name"
      prompt: "Unique name of your printer (no spaces)"
      private: false
      default: "OctoPrint"
    - name: "install_dir"
      prompt: "Install directory"
      private: false
      default: "/opt/OctoPrint"
    - name: "new_hostname"
      prompt: "Hostname"
      private: false
      default: "octoprint.local"
    - name: "port"
      prompt: "OctoPrint listening Port"
      private: false
      default: 5000
    - name: "webcam_port"
      prompt: "Webcam listening Port"
      private: false
      default: 8080
    - name: "install_haproxy"
      prompt: "Install haproxy [y/n]"
      private: false
      default: "y"
    - name: "install_touchui"
      prompt: "Install touchui [y/n]"
      private: false
      default: "y"
    - name: "install_z_offset"
      prompt: "Install Z Probe Offset Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_detail_progress"
      prompt: "Install Detailed Progress Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_filament_manager"
      prompt: "Install Filament Manager Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_print_history"
      prompt: "Install Print History Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_printtime_genius"
      prompt: "Install PrintTime Genius Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_slicer_thumbs"
      prompt: "Install Slicer Thumbnails Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_top_temp"
      prompt: "Install Top Temp Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_ui_custom"
      prompt: "Install UI Customiser Plugin [y/n]"
      private: false
      default: "y"
    - name: "install_cancel_objects"
      prompt: "Install Cancel Objects Plugin [y/n]"
      private: false
      default: "y"

  roles:
    - git
    - octoprint
