---
- hosts: all
  vars_prompt:
    - name: "printer_name"
      prompt: "Unique name of your printer (no spaces)"
      private: false
      default: "OctoPrint"
    - name: "install_dir"
      prompt: "Install directory"
      private: false
      default: "/opt/OctoPrint"
    - name: "new_hostname"
      prompt: "Hostname"
      private: false
      default: "octoprint.local"
    - name: "port"
      prompt: "OctoPrint listening Port"
      private: false
      default: 5000
    - name: "webcam_port"
      prompt: "Webcam listening Port"
      private: false
      default: 8080
    - name: "install_haproxy"
      prompt: "Install haproxy [y/n]"
      private: false
      default: "y"
    - name: "install_touchui"
      prompt: "Install touchui [y/n]"
      private: false
      default: "y"
  roles:
    - git
    - octoprint
